<?php
/**
 * @file
 * Integration module for ubercart and signup
 */

/**
 * Insert our own validation function into the signup form
 */
function uc_signup_form_signup_form_alter(&$form, &$form_state, $form_id) {
  $form['#validate'][] = 'uc_signup_form_validate';
}

/**
 * Modify the signup workflow if the signup node is a product 
 */
function uc_signup_form_validate($form, $form_state) {
  $node = $form_state['build_info']['args'][0];
  if (_uc_signup_node_check($node)) {
    $form_state['redirect'] = uc_cart_add_item($form_state['values']['nid'], 1, array('signup' => $form_state['values']));
  }
  drupal_set_message(t('You will be signed up to !node after checkout.', array('!node' => l($node->title, 'node/' . $node->nid))));
  // Bypass the form submission by going directly to the cart
  drupal_goto($form_state['redirect']);
}

/**
 * Process the signup once the checkout is complete
 */
function uc_signup_uc_checkout_complete($order, $account) {
  foreach ($order->products as $product) {
    if (_uc_signup_node_check($product->nid)) {
      $signup = $product->data['signup'];
      if ($signup['email_address'] == $account->mail) {
        signup_sign_up_user($signup);
      }
      else {
        module_load_include('inc', 'signup', 'includes/signup_form');
        $signup['signup_anon_mail'] = $signup['email_address'];
        if (signup_validate_anon_email($signup['nid'], $signup['signup_anon_mail'])) {
          $signup['uid'] = 0;
          unset($signup['email_address']);
          signup_sign_up_user($signup);
        }
        dsm($signup);
      }
    }
  }
}

/**
 * Helper function tells us if the node is a uc_signup node
 *
 * @param $node
 *   Either the nid or node object
 */
function _uc_signup_node_check(&$node) {
  if (is_numeric($node)) {
    $node = node_load($node);
  }
  return (isset($node->signup) && $node->signup && uc_product_is_product($node));
}
